[licenses]
unlicensed = "warn"
allow-osi-fsf-free = "both"
copyleft = "allow"
default = "warn"
unused-allowed-license = "warn"
confidence-threshold = 0.95
deny = [
    "Nokia",
    "BSD-2-Clause",
]
allow = [
    "Apache-2.0 WITH LLVM-exception",
    "MIT",
    "Apache-2.0"
]
