[package]
name = "weresocool_analyze"
version = "0.1.0"
authors = ["xasopheno <danny@xasopheno.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
weresocool_shared = { path = "../shared" }
