[package]
name = "opmap"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
hamcrest2 = "0.3.0"

[dependencies]
drain-while = "0.1.0"
