[package]
name = "weresocool_shared"
version = "1.0.47"
authors = ["Danny Meyer <weresocool@xasopheno.com>"]
edition = "2021"
description = "shared for WereSoCool"
license = "GPL-3.0" 
resolver="2"

[dependencies]
float-cmp = "0.8.0"
hex = "0.4.3"
num-rational = "0.4.1"
once_cell = "1.16.0"
rand = "0.8.5"
