[package]
name = "vorbis"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vorbis-encoder = "0.1.4"
hound = "3.4.0"
itertools = "0.10.3"
