name: Cool Tests

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: extractions/setup-just@v1
    - name: install dependancies
      run: | 
        sudo apt update
        sudo apt install -y libasound2-dev portaudio19-dev libportaudio2 libportaudiocpp0 pkg-config lame libmp3lame-dev vorbis-tools lld
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
          toolchain: stable
          components: clippy, rustfmt
          override: true
    - name: format
      run: just format
    - name: clippy 
      run: just clippy

  ubuntu:
    runs-on: ubuntu-latest

    steps:
    - name: setup dummy soundcard
      run: sudo echo "pcm.!default { type plug slave.pcm 'null' }" > $HOME/.asoundrc
    - uses: extractions/setup-just@v1
    - name: install dependancies
      run: | 
        sudo apt update
        sudo apt install -y libasound2-dev portaudio19-dev libportaudio2 libportaudiocpp0 pkg-config lame libmp3lame-dev vorbis-tools lld pulseaudio
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
          toolchain: stable
          override: true
    - name: run tests
      run: just test

  macos:
      runs-on: macos-latest 

      steps:
      - uses: extractions/setup-just@v1
      - name: install dependancies
        run: brew install portaudio pkg-config lame libvorbis
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            override: true
      - name: run tests
        run: just test
