name: Cool Tests on Macos

on: [push]

jobs:
  test_macos:
    runs-on: macos-latest 

    steps:
    - uses: extractions/setup-just@v1
    - name: install dependancies
      run: brew install portaudio pkg-config lame libvorbis
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
          toolchain: stable
          components: clippy, rustfmt
          override: true
    - name: format
      run: just format
    - name: clippy 
      run: just clippy
    - name: run tests
      run: just test
